spring.application.name=interview_feedback_system

spring.datasource.url=jdbc:postgresql://localhost:5432/ifms_database
spring.datasource.username=postgres
spring.datasource.password=49812884
# spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

spring.datasource.url=jdbc:postgresql://localhost:5432/ifms_database?sslmode=disable
server.port=9090

# This is for the Smtp and mail hog
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
